version: '2'

services:
   spark:
    image: docker.io/bitnami/spark:3
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4040:4040' #web
    volumes:
      - ./target:/vol

   spark-worker:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark

   nifi:
    image: docker.io/apache/nifi
    container_name: nifi
    ports: 
      - '8085:8080' #web
    volumes:
      - ./hdfs/config:/hdfs/config/
      - nifi:/opt/nifi/nifi-current/conf

   hdfs-master:
    build:
      context: ./hdfs
    image: hdfs-img
    container_name: hdfs-master
    environment:
      - HDFS_MODE=master
    depends_on:
      - hdfs-worker-1
      - hdfs-worker-2
      - hdfs-worker-3
    volumes:
      - ./data:/input
    ports:
      - 9870:9870

   hdfs-worker-1:
    build:
      context: ./hdfs
    image: hdfs-img
   hdfs-worker-2:
    build:
      context: ./hdfs
    image: hdfs-img
   hdfs-worker-3:
    build:
      context: ./hdfs
    image: hdfs-img

volumes:
  nifi:


